<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\HotelManagement.Domain\HotelManagement.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
	<PackageReference Include="AutoMapper" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Hotels\Specifications\" />
  </ItemGroup>

</Project>
