<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
	<PackageReference Include="Microsoft.OpenApi"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelManagement.Application\HotelManagement.Application.csproj" />
    <ProjectReference Include="..\HotelManagement.Domain\HotelManagement.Domain.csproj" />
    <ProjectReference Include="..\HotelManagement.Infrastructure\HotelManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
