<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
	<!-- Explicitly pin the transitive layer to overwrite the 2.0.0 vulnerability -->
	<PackageReference Include="Microsoft.OpenApi" Version="2.7.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelManagement.Application\HotelManagement.Application.csproj" />
    <ProjectReference Include="..\HotelManagement.Domain\HotelManagement.Domain.csproj" />
    <ProjectReference Include="..\HotelManagement.Infrastructure\HotelManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
